export const apps = [
	{ "name": "Settings", "category": "Utilities", "target": "settings", "icon": "settings", "iconSymbolic": "settings" },
	{ "name": "Files", "category": "Utilities", "target": "filemanager", "icon": "files", "iconSymbolic": "files" },
	{ "name": "Clock", "category": "Utilities", "target": "clock", "isClock": true, "iconSymbolic": "schedule" },
	{ "name": "Calculator", "category": "Utilities", "target": "calculator", "icon": "calculator", "iconSymbolic": "calculate" },
	{ "name": "Random", "category": "Utilities", "target": "random", "icon": "dice", "iconSymbolic": "casino" },
	{ "name": "Hash", "category": "Utilities", "target": "hash", "icon": "hash", "iconSymbolic": "tag" },
	{ "name": "Compress Pics", "category": "Utilities", "target": "imageconverter", "icon": "zip", "iconSymbolic": "folder_zip" },
	{ "name": "Encrypt Text", "category": "Utilities", "target": "safeencrypt", "icon": "key", "iconSymbolic": "key" },
	{ "name": "Terminal", "category": "Utilities", "target": "terminal", "icon": "terminal", "iconSymbolic": "terminal" },
	{ "name": "Desktop", "category": "Utilities", "target": "desktop", "icon": "computer", "iconSymbolic": "desktop_windows" },
	{ "name": "Notes", "category": "Create", "target": "quicknote", "icon": "note", "iconSymbolic": "note_stack" },
	{ "name": "Chat", "category": "Create", "target": "chat", "icon": "chat_ai", "iconSymbolic": "chat" },
	{ "name": "Generate Pics", "category": "Create", "target": "imagegenerator", "icon": "image", "iconSymbolic": "image" },
	{ "name": "Code", "category": "Create", "target": "codepad", "icon": "code", "iconSymbolic": "code" },
	{ "name": "Scrum Escape", "category": "Fun", "target": "https://scrumescapegamets.pages.dev/", "icon": "scrumescape", "iconSymbolic": "directions_run" },
	{ "name": "Alice's Gaze", "category": "Fun", "target": "https://alicegaze.pages.dev", "icon": "alicegaze", "iconSymbolic": "girl" },
	{ "name": "Portal", "category": "Fun", "target": "portal", "icon": "portal", "iconSymbolic": "circle" },
	{ "name": "Minecraft", "category": "Fun", "target": "https://irv77.github.io/AmplerLauncher/mc/1.12.2/", "icon": "minecraft", "iconSymbolic": "deployed_code" },
	{ "name": "Getting Over It", "category": "Fun", "target": "https://turbowarp.org/900802860/embed?autoplay&addons=remove-curved-stage-border%2Cpause", "icon": "scratchcat", "iconSymbolic": "cleaning_bucket" },
	{ "name": "Bad Piggies", "category": "Fun", "target": "https://map-l.github.io/play/bad-piggies/", "icon": "badpiggies", "iconSymbolic": "savings" },
	{ "name": "Baldi's Basics", "category": "Fun", "target": "https://map-l.github.io/play/baldis-basics/", "icon": "baldi", "iconSymbolic": "straighten" },
	{ "name": "GD", "category": "Fun", "target": "https://map-l.github.io/play/geometry-dash/", "icon": "gdash", "iconSymbolic": "change_history" },
	{ "name": "Deltarune", "category": "Fun", "target": "https://map-l.github.io/play/deltarune/", "icon": "deltarune", "iconSymbolic": "favorite" },
	{ "name": "Subway", "category": "Fun", "target": "https://map-l.github.io/play/subwaysurfers/", "icon": "ssurfers", "iconSymbolic": "subway" },
	{ "name": "Granny", "category": "Fun", "target": "https://map-l.github.io/play/granny/", "icon": "granny", "iconSymbolic": "elderly_woman" },
	{ "name": "Fractal", "category": "Fun", "target": "fractal", "icon": "fractal", "iconSymbolic": "ac_unit" },
	{ "name": "Mario", "category": "Fun", "target": "https://foss2016.github.io/", "icon": "questionblock", "iconSymbolic": "help_center" },
	{ "name": "HexGL", "category": "Fun", "target": "https://hexgl.bkcore.com/play/", "icon": "hexgl", "iconSymbolic": "sports_score" },
	{ "name": "2048", "category": "Fun", "target": "https://2048-opera-pwa.surge.sh/", "icon": "2048", "iconSymbolic": "looks_two" },
	{ "name": "Tetris", "category": "Fun", "target": "https://tmaiadev-tetra.netlify.app/", "icon": "tetra", "iconSymbolic": "grid_view" },
	{ "name": "Mahjong", "category": "Fun", "target": "https://mahjong.jull.dev/", "icon": "mahjong", "iconSymbolic": "payments" }
]