export const apps = [
	{ "name": "Settings", "category": "Utilities", "target": "settings", "icon": "settings" },
	{ "name": "Clock", "category": "Utilities", "target": "clock", "isClock": true },
	{ "name": "Calculator", "category": "Utilities", "target": "calculator", "icon": "calculator" },
	{ "name": "Random", "category": "Utilities", "target": "random", "icon": "dice" },
	{ "name": "Hash", "category": "Utilities", "target": "hash", "icon": "hash" },
	{ "name": "Compress Pics", "category": "Utilities", "target": "imageconverter", "icon": "zip" },
	{ "name": "Encrypt Text", "category": "Utilities", "target": "safeencrypt", "icon": "key" },
	{ "name": "Terminal", "category": "Utilities", "target": "terminal", "icon": "terminal" },
	{ "name": "Virtual PC", "category": "Utilities", "target": "https://browser7.win/", "icon": "computer" },
	{ "name": "Notes", "category": "Create", "target": "quicknote", "icon": "note" },
	{ "name": "Chat", "category": "Create", "target": "chat", "icon": "chat_ai" },
	{ "name": "Generate Pics", "category": "Create", "target": "imagegenerator", "icon": "image" },
	{ "name": "Code", "category": "Create", "target": "codepad", "icon": "code" },
	{ "name": "Scrum Escape", "category": "Fun", "target": "https://scrumescapegamets.pages.dev/", "icon": "scrumescape" },
	{ "name": "Alice's Gaze", "category": "Fun", "target": "https://alicegaze.pages.dev", "icon": "alicegaze" },
	{ "name": "Portal", "category": "Fun", "target": "portal", "icon": "portal" },
	{ "name": "Minecraft", "category": "Fun", "target": "https://irv77.github.io/AmplerLauncher/mc/1.12.2/", "icon": "minecraft" },
	{ "name": "Getting Over It", "category": "Fun", "target": "https://turbowarp.org/900802860/embed?autoplay&addons=remove-curved-stage-border%2Cpause", "icon": "scratchcat" },
	{ "name": "Bad Piggies", "category": "Fun", "target": "https://map-l.github.io/play/bad-piggies/", "icon": "badpiggies" },
	{ "name": "Baldi's Basics", "category": "Fun", "target": "https://map-l.github.io/play/baldis-basics/", "icon": "baldi" },
	{ "name": "GD", "category": "Fun", "target": "https://map-l.github.io/play/geometry-dash/", "icon": "gdash" },
	{ "name": "Deltarune", "category": "Fun", "target": "https://map-l.github.io/play/deltarune/", "icon": "deltarune" },
	{ "name": "Subway", "category": "Fun", "target": "https://map-l.github.io/play/subwaysurfers/", "icon": "ssurfers" },
	{ "name": "Granny", "category": "Fun", "target": "https://map-l.github.io/play/granny/", "icon": "granny" },
	{ "name": "Fractal", "category": "Fun", "target": "fractal", "icon": "fractal" },
	{ "name": "Mario", "category": "Fun", "target": "https://foss2016.github.io/", "icon": "questionblock" },
	{ "name": "HexGL", "category": "Fun", "target": "https://hexgl.bkcore.com/play/", "icon": "hexgl" },
	{ "name": "2048", "category": "Fun", "target": "https://2048-opera-pwa.surge.sh/", "icon": "2048" },
	{ "name": "Tetris", "category": "Fun", "target": "https://tmaiadev-tetra.netlify.app/", "icon": "tetra" },
	{ "name": "Mahjong", "category": "Fun", "target": "https://mahjong.jull.dev/", "icon": "mahjong" }
]